bind 0.0.0.0
protected-mode yes
port 6379
tcp-backlog 511
timeout 0
tcp-keepalive 300
notify-keyspace-events Ex

# Logging
loglevel notice
logfile ""

# Save configuration
save 900 1
save 300 10
save 60 10000

# Append Only Mode
appendonly yes
appendfilename "appendonly.aof"

# Security
requirepass password